Create create-a-chase-pay-transaction.py
AuthorizeNet/sample-code-python pull request #48
Opened 2018-12-11 07:46 UTC by kapilkumar99

added saple code for chase pay transaction

2018-12-11 11:29 UTC, gnongsie requested changes

2018-12-11 11:46 UTC, kapilkumar99 commented on PaymentTransactions/create-a-chase-pay-transaction.py
> +    transactionrequest.amount = Decimal ('1.5')
Added two digits after decimal point

2018-12-12 08:17 UTC, gnongsie approved these changes

2018-12-12 08:17 UTC, gnongsie commented
Ready to merge

2018-12-13 08:11 UTC, merged

2025-01-29 04:47 UTC, Elizabeth-has commented
d45f9d8aa6a2b24049ca672e680151a6f9b970ec

2025-01-29 04:48 UTC, Elizabeth-has approved these changes